// Mock data for Slatch Pharmaceuticals. In a real deployment this would come
// from a CMS or database.

const level2Map = {
  "digestive-stomach-disorders": [
    "Acidity & Indigestion",
    "Constipation",
    "Bloating & Gas",
    "Stomach Discomfort",
  ],
  "liver-gallbladder-disorders": [
    "Liver Support",
    "Gallbladder Health",
    "Jaundice & Detox",
    "Hepatic Care",
  ],
  "kidney-urinary-disorders": [
    "Kidney Support",
    "Urinary Tract Care",
    "Stone Prevention",
    "Fluid Balance",
  ],
  "diabetes-endocrine-metabolic-disorders": [
    "Blood Sugar Balance",
    "Metabolic Support",
    "Hormonal Health",
    "Weight Management",
  ],
  "heart-blood-circulatory-disorders": [
    "Heart Health",
    "Blood Circulation",
    "Blood Pressure Support",
    "Cardiac Wellness",
  ],
  "respiratory-lung-disorders": [
    "Asthma & Bronchitis",
    "Cough & Cold",
    "Breathing Support",
    "Lung Wellness",
  ],
  "eyes-ears-nose-throat-disorders": [
    "Eye Care",
    "Ear Care",
    "Nasal Health",
    "Throat Comfort",
  ],
  "brain-mental-health-sleep-disorders": [
    "Stress & Anxiety",
    "Sleep Support",
    "Mental Focus",
    "Calmness & Relaxation",
  ],
  "joint-bone-muscle-nerve-disorders": [
    "Joint Pain",
    "Muscle Comfort",
    "Nerve Support",
    "Bone & Spine Care",
  ],
  "skin-hair-nails-disorders": [
    "Skin Care",
    "Hair Health",
    "Nail Health",
    "Acne & Glow",
  ],
  "mens-health-sexual-reproductive-disorders": [
    "Male Vitality",
    "Sexual Wellness",
    "Reproductive Health",
    "Performance & Stamina",
  ],
  "womens-health-hormonal-reproductive-disorders": [
    "Hormonal Balance",
    "Menstrual Support",
    "Reproductive Wellness",
    "Women’s Vitality",
  ],
  "childrens-health-immunity": [
    "Kids’ Immunity",
    "Growth & Vitality",
    "General Wellness",
    "Seasonal Care",
  ],
  "infections-fever-seasonal-illnesses": [
    "Fever Care",
    "Seasonal Relief",
    "Immune Recovery",
    "Infection Support",
  ],
  "weight-energy-general-weakness-performance": [
    "Energy & Stamina",
    "Weight Balance",
    "Weakness Recovery",
    "General Vitality",
  ],
  "elderly-care-chronic-conditions": [
    "Chronic Care",
    "Mobility Support",
    "General Wellness",
    "Senior Vitality",
  ],
};

export const categories = [
  {
    slug: "digestive-stomach-disorders",
    name: "Digestive & Stomach Disorders",
    icon: "Stomach",
    color: "#D97706",
    description:
      "Herbal formulations to support digestion, acidity, bloating and stomach comfort.",
    level: 1,
    children: level2Map["digestive-stomach-disorders"],
  },
  {
    slug: "liver-gallbladder-disorders",
    name: "Liver & Gallbladder Disorders",
    icon: "Liver",
    color: "#EA580C",
    description: "Traditional remedies formulated to support liver and gallbladder health.",
    level: 1,
    children: level2Map["liver-gallbladder-disorders"],
  },
  {
    slug: "kidney-urinary-disorders",
    name: "Kidney & Urinary Disorders",
    icon: "Kidney",
    color: "#2563EB",
    description: "Herbal support for kidney function and the urinary tract.",
    level: 1,
    children: level2Map["kidney-urinary-disorders"],
  },
  {
    slug: "diabetes-endocrine-metabolic-disorders",
    name: "Diabetes, Endocrine & Metabolic Disorders",
    icon: "Diabetes",
    color: "#7C3AED",
    description:
      "Formulations traditionally used to support healthy blood sugar, endocrine balance and metabolism.",
    level: 1,
    children: level2Map["diabetes-endocrine-metabolic-disorders"],
  },
  {
    slug: "heart-blood-circulatory-disorders",
    name: "Heart, Blood & Circulatory Disorders",
    icon: "Heart",
    color: "#DC2626",
    description: "Herbal support for heart, blood and circulatory wellbeing.",
    level: 1,
    children: level2Map["heart-blood-circulatory-disorders"],
  },
  {
    slug: "respiratory-lung-disorders",
    name: "Respiratory & Lung Disorders",
    icon: "Lungs",
    color: "#0284C7",
    description: "Herbal support for the respiratory system and lung health.",
    level: 1,
    children: level2Map["respiratory-lung-disorders"],
  },
  {
    slug: "eyes-ears-nose-throat-disorders",
    name: "Eyes, Ears, Nose & Throat Disorders",
    icon: "Throat",
    color: "#0D9488",
    description: "Traditional support for the eyes, ears, nose and throat.",
    level: 1,
    children: level2Map["eyes-ears-nose-throat-disorders"],
  },
  {
    slug: "brain-mental-health-sleep-disorders",
    name: "Brain, Mental Health & Sleep Disorders",
    icon: "Pain",
    color: "#4F46E5",
    description: "Herbal support for mental calmness, focus and healthy sleep patterns.",
    level: 1,
    children: level2Map["brain-mental-health-sleep-disorders"],
  },
  {
    slug: "joint-bone-muscle-nerve-disorders",
    name: "Joint, Bone, Muscle & Nerve Disorders",
    icon: "Joint",
    color: "#65A30D",
    description: "Herbal support for joints, bones, muscles and nerves.",
    level: 1,
    children: level2Map["joint-bone-muscle-nerve-disorders"],
  },
  {
    slug: "skin-hair-nails-disorders",
    name: "Skin, Hair & Nails Disorders",
    icon: "Skin",
    color: "#DB2777",
    description: "Herbal care for skin, hair and nail health.",
    level: 1,
    children: level2Map["skin-hair-nails-disorders"],
  },
  {
    slug: "mens-health-sexual-reproductive-disorders",
    name: "Men’s Health, Sexual & Reproductive Disorders",
    icon: "MensHealth",
    color: "#0891B2",
    description: "Herbal formulations tailored to men’s health, sexual wellbeing and reproductive support.",
    level: 1,
    children: level2Map["mens-health-sexual-reproductive-disorders"],
  },
  {
    slug: "womens-health-hormonal-reproductive-disorders",
    name: "Women’s Health, Hormonal & Reproductive Disorders",
    icon: "WomensHealth",
    color: "#C026D3",
    description: "Herbal support for women’s health, hormones and reproductive wellbeing.",
    level: 1,
    children: level2Map["womens-health-hormonal-reproductive-disorders"],
  },
  {
    slug: "childrens-health-immunity",
    name: "Children’s Health & Immunity",
    icon: "Fertility",
    color: "#CA8A04",
    description: "Support for children’s wellness, immunity and everyday vitality.",
    level: 1,
    children: level2Map["childrens-health-immunity"],
  },
  {
    slug: "infections-fever-seasonal-illnesses",
    name: "Infections, Fever & Seasonal Illnesses",
    icon: "Throat",
    color: "#E11D48",
    description: "Herbal formulations traditionally used to support recovery and seasonal comfort.",
    level: 1,
    children: level2Map["infections-fever-seasonal-illnesses"],
  },
  {
    slug: "weight-energy-general-weakness-performance",
    name: "Weight, Energy, General Weakness & Performance",
    icon: "Diabetes",
    color: "#9333EA",
    description: "Support for energy, stamina, weight balance and general vitality.",
    level: 1,
    children: level2Map["weight-energy-general-weakness-performance"],
  },
  {
    slug: "elderly-care-chronic-conditions",
    name: "Elderly Care & Chronic Conditions",
    icon: "Heart",
    color: "#57534E",
    description: "Traditional support for everyday wellbeing in older age and chronic care.",
    level: 1,
    children: level2Map["elderly-care-chronic-conditions"],
  },
];

export const products = [
  {
    slug: "khameera-ghaozaban-ambari",
    name: "Khameera Ghaozaban Ambari",
    qd: "QD 536",
    category: "heart-cardiovascular-disorders",
    price: 850,
    form: "Syrup",
    size: "125 ml",
    description:
      "A classic Unani formulation traditionally used as a cardiac and nervine tonic, helping to strengthen the heart and calm the nerves.",
    usage: "Take 5-10 ml twice daily, or as directed by your physician.",
    ingredients: "Ghaozaban, Amber, Gold leaf, Sandal, and other traditional herbs.",
  },
  {
    slug: "majun-mughalliz-jawahir",
    name: "Majun Mughalliz Jawahir",
    qd: "QD 3068",
    category: "mens-health",
    price: 1450,
    form: "Paste (Majun)",
    size: "125 g",
    description:
      "A traditional Jawahir-based Majun formulated to support general vigor and vitality in men.",
    usage: "Take 3-5 g once daily with milk, or as directed by your physician.",
    ingredients: "Jawahir (gem-based) compound blended with traditional herbs and gum base.",
  },
  {
    slug: "safi-dam-e-kaif",
    name: "Safi Dam-e-Kaif",
    qd: "QD 192",
    category: "skin-disorders",
    price: 480,
    form: "Syrup",
    size: "200 ml",
    description:
      "A blood-purifying herbal syrup traditionally used to support clear, healthy skin.",
    usage: "Take 10-15 ml twice daily before meals, or as directed by your physician.",
    ingredients: "Neem, Manjishtha, Chirata and other blood-purifying herbs.",
  },
  {
    slug: "khajoorina-muntakhib",
    name: "Khajoorina Muntakhib",
    qd: "QD 560",
    category: "mens-health",
    price: 620,
    form: "Syrup",
    size: "125 ml",
    description:
      "A date-palm based tonic traditionally used to support strength and general wellbeing.",
    usage: "Take 10 ml twice daily, or as directed by your physician.",
    ingredients: "Khajoor (date palm) extract with supporting herbs.",
  },
  {
    slug: "jawarish-jalinoos",
    name: "Jawarish Jalinoos",
    qd: "QD 214",
    category: "digestive-stomach-disorders",
    price: 390,
    form: "Paste (Jawarish)",
    size: "125 g",
    description:
      "A digestive Jawarish traditionally used to relieve acidity, bloating and indigestion.",
    usage: "Take 5 g after meals, or as directed by your physician.",
    ingredients: "Amla, cardamom, cinnamon and other digestive herbs.",
  },
  {
    slug: "arq-mundi",
    name: "Arq Mundi",
    qd: "QD 118",
    category: "digestive-stomach-disorders",
    price: 260,
    form: "Distillate (Arq)",
    size: "500 ml",
    description: "A cooling herbal distillate traditionally used to soothe the digestive system.",
    usage: "Take 30-40 ml once or twice daily, or as directed by your physician.",
    ingredients: "Coriander seed distillate blended with cooling herbs.",
  },
  {
    slug: "sharbat-bazoori-motadil",
    name: "Sharbat Bazoori Motadil",
    qd: "QD 344",
    category: "heart-cardiovascular-disorders",
    price: 410,
    form: "Syrup (Sharbat)",
    size: "300 ml",
    description:
      "A cooling herbal Sharbat traditionally used to protect the body from heat and support the heart.",
    usage: "Mix 20-30 ml in a glass of water and take once or twice daily.",
    ingredients: "Rose, Sandal, Khas and other cooling herbs.",
  },
  {
    slug: "majun-najah",
    name: "Majun Najah",
    qd: "QD 402",
    category: "digestive-stomach-disorders",
    price: 350,
    form: "Paste (Majun)",
    size: "125 g",
    description: "A traditional laxative Majun used to relieve occasional constipation.",
    usage: "Take 5-10 g at bedtime with water, or as directed by your physician.",
    ingredients: "Senna, Tamarind and other traditional laxative herbs.",
  },
  {
    slug: "roghan-badam-shirin",
    name: "Roghan Badam Shirin",
    qd: "QD 077",
    category: "hair-scalp-disorders",
    price: 520,
    form: "Oil",
    size: "100 ml",
    description: "Sweet almond oil traditionally used to nourish hair and the scalp.",
    usage: "Massage gently into the scalp and hair, 2-3 times a week.",
    ingredients: "Pure sweet almond (Badam Shirin) oil.",
  },
  {
    slug: "zimad-mafasil",
    name: "Zimad Mafasil",
    qd: "QD 261",
    category: "joint-bone-muscular-disorders",
    price: 380,
    form: "Ointment (Zimad)",
    size: "50 g",
    description:
      "A warming herbal ointment traditionally applied to support joint and muscular comfort.",
    usage: "Apply gently to the affected area 2-3 times daily.",
    ingredients: "Ajwain, Sonth and other warming herbs in an ointment base.",
  },
  {
    slug: "sharbat-unnab",
    name: "Sharbat Unnab",
    qd: "QD 305",
    category: "cough-cold-throat",
    price: 340,
    form: "Syrup (Sharbat)",
    size: "300 ml",
    description: "A soothing herbal Sharbat traditionally used for cough and throat irritation.",
    usage: "Mix 20 ml in warm water and take 2-3 times daily.",
    ingredients: "Unnab (Jujube), Banafsha and other soothing herbs.",
  },
  {
    slug: "khamira-marwareed",
    name: "Khamira Marwareed",
    qd: "QD 452",
    category: "heart-cardiovascular-disorders",
    price: 980,
    form: "Paste (Khamira)",
    size: "125 g",
    description:
      "A pearl-based Khamira traditionally used as a general tonic for heart and body strength.",
    usage: "Take 3-5 g once daily, or as directed by your physician.",
    ingredients: "Pearl (Marwareed) preparation with supporting herbs.",
  },
  {
    slug: "qurs-mudir",
    name: "Qurs Mudir",
    qd: "QD 133",
    category: "kidney-urinary-disorders",
    price: 290,
    form: "Tablets",
    size: "50 tablets",
    description: "Herbal tablets traditionally used to support healthy kidney and urinary function.",
    usage: "Take 1-2 tablets twice daily with water, or as directed by your physician.",
    ingredients: "Kasni, Bark of Kateeri and other diuretic herbs.",
  },
  {
    slug: "safoof-mohazzil",
    name: "Safoof Mohazzil",
    qd: "QD 188",
    category: "diabetes-metabolic-disorders",
    price: 420,
    form: "Powder (Safoof)",
    size: "100 g",
    description: "An herbal powder traditionally used to support healthy weight and metabolism.",
    usage: "Take 3-5 g twice daily with water, or as directed by your physician.",
    ingredients: "Traditional metabolic-support herb blend.",
  },
  {
    slug: "arq-gulab",
    name: "Arq Gulab",
    qd: "QD 010",
    category: "skin-disorders",
    price: 220,
    form: "Distillate (Arq)",
    size: "500 ml",
    description: "Pure rose water distillate traditionally used to refresh and soothe the skin.",
    usage: "Apply topically with cotton, or take 15-20 ml with water.",
    ingredients: "100% pure rose (Gulab) distillate.",
  },
  {
    slug: "majun-falasifa",
    name: "Majun Falasifa",
    qd: "QD 505",
    category: "respiratory-lung-disorders",
    price: 460,
    form: "Paste (Majun)",
    size: "125 g",
    description: "An herbal Majun traditionally used to support respiratory comfort.",
    usage: "Take 5 g twice daily, or as directed by your physician.",
    ingredients: "Traditional respiratory-support herb blend.",
  },
  {
    slug: "habb-e-jawahar",
    name: "Habb-e-Jawahar",
    qd: "QD 620",
    category: "pain-inflammation",
    price: 540,
    form: "Pills (Habb)",
    size: "30 pills",
    description: "Herbal pills traditionally used for general pain and inflammation relief.",
    usage: "Take 1 pill once or twice daily, or as directed by your physician.",
    ingredients: "Traditional Jawahar-based compound with supporting herbs.",
  },
  {
    slug: "sharbat-niloofar",
    name: "Sharbat Niloofar",
    qd: "QD 275",
    category: "womens-health",
    price: 380,
    form: "Syrup (Sharbat)",
    size: "300 ml",
    description: "A cooling Sharbat traditionally used to support general wellbeing in women.",
    usage: "Mix 20-30 ml in water and take once or twice daily.",
    ingredients: "Niloofar (water lily) and other cooling herbs.",
  },
  {
    slug: "majun-supari-pak",
    name: "Majun Supari Pak",
    qd: "QD 611",
    category: "fertility-reproductive-health",
    price: 890,
    form: "Paste (Majun)",
    size: "125 g",
    description: "A traditional formulation used to support reproductive wellness.",
    usage: "Take 5 g once daily with milk, or as directed by your physician.",
    ingredients: "Supari Pak compound with traditional supporting herbs.",
  },
  {
    slug: "roghan-surkh",
    name: "Roghan Surkh",
    qd: "QD 099",
    category: "joint-bone-muscular-disorders",
    price: 480,
    form: "Oil",
    size: "100 ml",
    description: "A red herbal oil traditionally used for massage to support joint comfort.",
    usage: "Massage gently onto the affected area once or twice daily.",
    ingredients: "Traditional warming oil blend.",
  },
  {
    slug: "sharbat-e-aab-e-resha",
    name: "Sharbat-e-Aab-e-Resha",
    qd: "QD 322",
    category: "blood-pressure-circulation",
    price: 400,
    form: "Syrup (Sharbat)",
    size: "300 ml",
    description: "An herbal Sharbat traditionally used to support healthy circulation.",
    usage: "Mix 20 ml in water and take once or twice daily.",
    ingredients: "Traditional circulation-support herb blend.",
  },
  {
    slug: "itrifal-ustukhuddus",
    name: "Itrifal Ustukhuddus",
    qd: "QD 234",
    category: "digestive-stomach-disorders",
    price: 360,
    form: "Paste (Itrifal)",
    size: "125 g",
    description: "A classic Itrifal traditionally used to support digestion and mental clarity.",
    usage: "Take 5 g once daily with water, or as directed by your physician.",
    ingredients: "Ustukhuddus, Halela and other traditional herbs.",
  },
  {
    slug: "sat-podina",
    name: "Sat Podina",
    qd: "QD 041",
    category: "digestive-stomach-disorders",
    price: 180,
    form: "Crystals (Sat)",
    size: "10 g",
    description: "Mint crystals traditionally used to relieve gas and indigestion.",
    usage: "Take a pinch with water after meals, or as directed by your physician.",
    ingredients: "Pure peppermint (Podina) crystals.",
  },
  {
    slug: "habb-e-suranjan",
    name: "Habb-e-Suranjan",
    qd: "QD 588",
    category: "joint-bone-muscular-disorders",
    price: 410,
    form: "Pills (Habb)",
    size: "30 pills",
    description: "Herbal pills traditionally used to support joint comfort.",
    usage: "Take 1 pill twice daily, or as directed by your physician.",
    ingredients: "Suranjan Shirin and other traditional joint-support herbs.",
  },
  {
    slug: "arq-ajeeb",
    name: "Arq Ajeeb",
    qd: "QD 152",
    category: "cough-cold-throat",
    price: 240,
    form: "Distillate (Arq)",
    size: "500 ml",
    description: "An herbal distillate traditionally used to relieve cold symptoms.",
    usage: "Take 30-40 ml once or twice daily, or as directed by your physician.",
    ingredients: "Traditional cold-relief herb blend.",
  },
  {
    slug: "majun-ushba",
    name: "Majun Ushba",
    qd: "QD 469",
    category: "kidney-urinary-disorders",
    price: 470,
    form: "Paste (Majun)",
    size: "125 g",
    description: "A blood-purifying Majun traditionally used to support urinary health.",
    usage: "Take 5-10 g once daily, or as directed by your physician.",
    ingredients: "Ushba root and other traditional purifying herbs.",
  },
  {
    slug: "sharbat-faulad",
    name: "Sharbat Faulad",
    qd: "QD 355",
    category: "womens-health",
    price: 420,
    form: "Syrup (Sharbat)",
    size: "300 ml",
    description: "An iron-rich herbal Sharbat traditionally used to support general strength.",
    usage: "Take 15-20 ml twice daily, or as directed by your physician.",
    ingredients: "Iron (Faulad) preparation with supporting herbs.",
  },
  {
    slug: "roghan-zard-chob",
    name: "Roghan Zard Chob",
    qd: "QD 063",
    category: "skin-disorders",
    price: 340,
    form: "Oil",
    size: "50 ml",
    description: "A turmeric-based oil traditionally applied to support healthy-looking skin.",
    usage: "Apply gently to the affected area once daily.",
    ingredients: "Zard Chob (turmeric) extract in an oil base.",
  },
  {
    slug: "majun-arad-khurma",
    name: "Majun Arad Khurma",
    qd: "QD 517",
    category: "mens-health",
    price: 780,
    form: "Paste (Majun)",
    size: "125 g",
    description: "A date-based Majun traditionally used to support strength and vitality.",
    usage: "Take 5 g once daily with milk, or as directed by your physician.",
    ingredients: "Date (Khurma) preparation with supporting herbs.",
  },
];

export function getCategoryBySlug(slug) {
  return categories.find((c) => c.slug === slug);
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug) {
  return products.filter((p) => p.category === slug);
}

export function searchAll(query) {
  const q = query.trim().toLowerCase();
  if (!q) return { products: [], categories: [] };
  return {
    products: products.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.qd.toLowerCase().includes(q) ||
        p.slug.toLowerCase().includes(q)
    ),
    categories: categories.filter(
      (c) =>
        c.name.toLowerCase().includes(q) || c.description.toLowerCase().includes(q)
    ),
  };
}

export function formatPKR(amount) {
  return `Rs. ${amount.toLocaleString("en-PK")}`;
}
